AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template for HafaRetails"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "hafaretails-web"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "HafaRetails_Products"
      AttributeDefinitions:
        - AttributeName: "productID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "productID"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
